version: "2"

linters:
  settings:
    errcheck:
      exclude-functions:
        - (io.Closer).Close
        - (*database/sql.Rows).Close
        - (io.ReadCloser).Close
        - fmt.Fprintf
        - fmt.Fprint
        - fmt.Fprintln
        - (*os.File).Close