package models

import (
	"encoding/json"

	"github.com/charmbracelet/bubbles/spinner"
)

type GlobalState struct {
	currentPage string
	spinner     spinner.Model
	loading     bool
	quickAction bool
}

type Selection struct {
	Choice string
}

type Room struct {
	Id      string
	Name    string
	NbUsers int
	Price   float64
}

type UnavailableSlot struct {
	Title string `json:"Title"`
	Start string `json:"Start"`
	End   string `json:"End"`
}

type RoomUsage struct {
	Name      string
	Id        string
	UsedSlots []UnavailableSlot
}

type Request struct {
	UserId      string
	Command     string
	Text        string
	ResponseUrl string
	TriggerId   string
}

type InteractionDiscovery struct {
	User struct {
		ID string `json:"id"`
	} `json:"user"`
	State struct {
		Values json.RawMessage `json:"values"`
	} `json:"state"`
	ResponseURL string `json:"response_url"`
	Actions     []struct {
		ActionID string `json:"action_id"`
	}
}

type AutoGenerated struct {
	Type string `json:"type"`
	User struct {
		ID       string `json:"id"`
		Username string `json:"username"`
		Name     string `json:"name"`
		TeamID   string `json:"team_id"`
	} `json:"user"`
	APIAppID  string `json:"api_app_id"`
	Token     string `json:"token"`
	Container struct {
		Type        string `json:"type"`
		MessageTs   string `json:"message_ts"`
		ChannelID   string `json:"channel_id"`
		IsEphemeral bool   `json:"is_ephemeral"`
	} `json:"container"`
	TriggerID string `json:"trigger_id"`
	Team      struct {
		ID     string `json:"id"`
		Domain string `json:"domain"`
	} `json:"team"`
	Enterprise          any  `json:"enterprise"`
	IsEnterpriseInstall bool `json:"is_enterprise_install"`
	Channel             struct {
		ID   string `json:"id"`
		Name string `json:"name"`
	} `json:"channel"`
	State struct {
		Values struct {
			Email struct {
				Email struct {
					Type  string `json:"type"`
					Value string `json:"value"`
				} `json:"email"`
			} `json:"email"`
			Password struct {
				Password struct {
					Type  string `json:"type"`
					Value string `json:"value"`
				} `json:"password"`
			} `json:"password"`
		} `json:"values"`
	} `json:"state"`
	ResponseURL string `json:"response_url"`
	Actions     []struct {
		ActionID string `json:"action_id"`
		BlockID  string `json:"block_id"`
		Text     struct {
			Type  string `json:"type"`
			Text  string `json:"text"`
			Emoji bool   `json:"emoji"`
		} `json:"text"`
		Value    string `json:"value"`
		Type     string `json:"type"`
		ActionTs string `json:"action_ts"`
	} `json:"actions"`
}
